### ISSUE TITLE
getValuesAs 

### ISSUE THREAD

**Issue by samih123** [HarryvL/fcVM-workbench#3]
Hi,
Self compiled  FreeCAD +  fcVM gives error:

Traceback (most recent call last):
  File "/home/sami/.local/share/FreeCAD/Mod/fcVM-workbench/InitGui.py", line 207, in start_clicked
    exec(fcVM_macro)
  File "<string>", line 108, in <module>
  File "/home/sami/.local/share/FreeCAD/Mod/fcVM-workbench/source code/fcVM.py", line 286, in setUpInput
    F = float(App.Units.Quantity(obj.Force.getValuesAs('N')))
                                 ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Base.Quantity' object has no attribute 'getValuesAs'. Did you mean: 'getValueAs'?

After chancing getValuesAs to getValueAs  fcVM works fine.

**Comment by luzpaz** [comment]
Is this still relevant ?

**Comment by samih123** [comment]
Yes, I dont know much about python, but for some reason the self-compiled freecad gives this error.

**Comment by HarryvL** [comment]
Strangely enough, I didn't get this error in 0.21, but do get it in 1.0. Changing chancing getValuesAs to getValueAs fixes the problem.

**Comment by HarryvL** [comment]
I updated the repo to fix this problem
